website/status/urls.py
from django.urls import path
from . import views

app_name='status'
urlpatterns = [
    # /status
    path('', views.index,name="index"),
    path('details',views.details,name="details"),
    path('custlogin',views.custlogin,name="custlogin"),
    path('shares',views.shares,name="shares"),
    path('fixedDeposits',views.fixedDeposits,name="fixedDeposits"),
    path('Loanuser',views.loanuser,name="loanuser"),
    path('Investment',views.Investment,name="Investment"),
    path('committee',views.committee,name="committee"),
    path('pdf',views.GeneratePdf.as_view(),name="GeneratePdf"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from status import views
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('csadmin/', include('csadmin.urls')),
    path('',include('landingPage.urls')),
    #path('',Home.as_view()),
]

website/status/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','password']

class change_MoneyForm(forms.Form):
    new_amount = forms.IntegerField()

Loan_choice=[
    ('normal_loan','Normal Loan'),
    ('emergency_loan', 'Emergency Loan'),
]

class LoanReqForm(forms.Form):

    loanChoice = forms.CharField(widget=forms.RadioSelect(choices=Loan_choice))
    loan_amount = forms.IntegerField()

website/status/views.py
from django.shortcuts import render
#models
from status.models import Account,interests,Notification,FixedDeposits,HistorylongLoan,HistoryemerLoan,HistoryFd
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from django.contrib import messages
#forms
from status.forms import change_MoneyForm,LoanReqForm

#for date and time
import datetime
from dateutil import relativedelta

#for E-mail
from django.core.mail import send_mail
import smtplib

#for PDF
from status.utils import render_to_pdf

from csadmin import views

def error_404_view(request, exception):
    data = {"name": "ThePythonDjango.com"}
    return render(request,'status/error_404.html', data)

def notisave(notificationmessage,senderid):
    notification=Notification()
    notification.notimessage=notificationmessage
    notification.sender_id=senderid
    notification.save()


def custlogin(request):
    if request.user.is_staff:
        return redirect('/csadmin/')
    else:
        return redirect('/status/details')




def index(request):
    '''code for fetching any data from the models
    for embedding it into the html template
    to be called here and saved into variables and then
    pass it as the third parameter to the render Function
    '''

    #space left for fetcing data from the models and populating the teplates

    return render(request,'cards.html')

@login_required
def details(request):
    '''this view return the details of the logged in user '''

    current_user_id=request.user.username
    currentuserid=request.user.id
    name=str(Account.name)
    Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()
    fdcount=FixedDeposits.objects.filter(username_id=currentuserid).count()
    Interests=interests.objects.all().last()


#for changing the monthly monthlyDeduction which shld be in the multiple of Rs. 500
    Final_new_change =0
    if request.method=="POST":
        New_money_change = change_MoneyForm(request.POST)

        if New_money_change.is_valid():
            Final_new_change = New_money_change.cleaned_data['new_amount']

            subject = 'This guy wants to change his monthly deduction'
            message = "Change Monthly Deduction of " + Accountholder.name +" to Rs."+str(Final_new_change)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['jatinhdalvi@gmail.com','aashulikabra@gmail.com','champtem11@gmail.com']
            messages.success(request, 'Mail sent')
            notisave(str(message),request.user.id)
            send_mail( subject, message, email_from, recipient_list )
            print("mail sent")

    else:
        New_money_change=change_MoneyForm()
    print(Final_new_change)

#calculating totalInvestment
    date = Accountholder.dateofjoining
    print("loan")
    context={
    'name':name,
    'Accountholder':Accountholder,
    'fdcount':fdcount,
    'date':date,
    'Interests':Interests,
    'dashboard':"active",
    }

    return render(request,'dashboard.html',context=context)

@login_required
def committee(request):
        context={
        'committee':"active",
        }
        return render(request,'committee.html',context=context)


@login_required
def shares(request):

    current_user_id=request.user.username
    Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()
    print("boo")
    print(Accountholder.id)
    context={
        'Accountholder':Accountholder,
        'share':"active",
    }

    return render (request,'shares.html',context=context)

@login_required
def fixedDeposits(request):

    current_user_id=request.user.username
    currentuserid=request.user.id
    Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()
    userF=FixedDeposits.objects.filter(username_id=currentuserid)
    fdcount=FixedDeposits.objects.filter(username_id=currentuserid).count()
    print(fdcount)
    print(userF)
    print("Upar")
    # userF=FixedDeposits.objects.filter(id__id__icontains=Accountholder.id).get()
    Interests=interests.objects.all().last()

    context={
        'Accountholder':Accountholder,
        'Interests':Interests,
        'fdcount':fdcount,
        'userF':userF,
        'fixed':"active",
    }
    return render (request,'fixedDeposits.html',context=context)

@login_required
def loanuser(request):
    current_user_id = request.user.username
    currentuserid=request.user.id
    Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()
    Longloans=HistorylongLoan.objects.filter(username=currentuserid)
    countlongloans=Longloans.count()
    Emerloans=HistoryemerLoan.objects.filter(username=currentuserid)
    countemerloans=Emerloans.count()
    print(countlongloans)
    print(countemerloans)
    print("just")
    print(current_user_id)
    type="success"
    eligibility=""

    if Accountholder.longloanbalance > Accountholder.longloanamount*50/100:
        print("Not eligible for loan")
        eligibility="No"
    else:
        print("eligible for loan")
        eligibility="Yes"

#Email for choice on request in taking loan
    if request.method=="POST":
        loanreq = LoanReqForm(request.POST)
        if loanreq.is_valid():
            Loan_Amount=str(loanreq.cleaned_data['loan_amount'])
            print(Loan_Amount)
            print(Accountholder.teachingstaff)
            loan_amount=int(Loan_Amount)
            print(loan_amount)
            if eligibility=="Yes":
                if Accountholder.teachingstaff==True and loan_amount <= 1200000 :
                    print(Loan_Amount)
                    Loan_Choice=loanreq.cleaned_data['loanChoice']
                    print(Loan_Choice)
                    subject = 'This guy wants a loan'
                    message = Accountholder.name +" has requested for "+ Loan_Choice +" of Rs "+Loan_Amount
                    email_from = settings.EMAIL_HOST_USER
                    type="success"
                    recipient_list = ['jatinhdalvi@gmail.com','aashulikabra@gmail.com','champtem11@gmail.com']
                    messages.success(request, 'Mail sent')
                    notisave(str(message),request.user.id)
                    send_mail( subject, message, email_from, recipient_list )
                    print("mail sent")
                elif Accountholder.nonteachingstaff==True and loan_amount <= 900000:
                    print(Loan_Amount)
                    Loan_Choice=loanreq.cleaned_data['loanChoice']
                    print(Loan_Choice)
                    subject = 'This guy wants a loan'
                    message = Accountholder.name +" has requested for "+ Loan_Choice +" of Rs "+Loan_Amount
                    email_from = settings.EMAIL_HOST_USER
                    type="success"
                    recipient_list = ['jatinhdalvi@gmail.com','aashulikabra@gmail.com','champtem11@gmail.com']
                    messages.success(request, 'Mail sent')
                    notisave(str(message),request.user.id)
                    send_mail( subject, message, email_from, recipient_list )
                    print("mail sent")

                else:
                    loanreq=LoanReqForm()
                    messages.error(request, 'Enter a valid amount')
                    type="danger"
            else:
                messages.error(request, 'pay 50% of loan first')
                type="danger"


    context={
        'Accountholder':Accountholder,
        'Emerloans':Emerloans,
        'Longloans':Longloans,
        'countlongloans':countlongloans,
        'countemerloans':countemerloans,
        'loan':"active",
        'type':type,
        'eligibility':eligibility,
    }
    return render (request,'Loansuser.html',context=context)

@login_required
def Investment(request):
    current_user_id = request.user.username
    Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()

    context={
    'Accountholder':Accountholder,
    'investment':"active",
    }
    return render (request,'Investment.html',context=context)

#use http response here it'll work
# for pdf stuff Using WeasyPrint

class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        template = get_template('pdf.html')
        current_user_id=request.user.username
        Accountholder=Account.objects.filter(username__username__icontains=current_user_id).get()
        context ={
            'Accountholder':Accountholder,
        }
        html = template.render(context)
        pdf = render_to_pdf('pdf.html', context)
        return HttpResponse(pdf, content_type='application/pdf')

website/status/templates/Loansuser.html
{%extends 'details.html'%}
{% load humanize %}

<!-- {%block title%}Loans{%endblock%} -->

{%block content%}
<main role="main" class="col-md-9 col-lg-12 px-4">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h1><b class="card-title">Loan Details</b></h1>

            {% if Accountholder.islongloantaken or Accountholder.isloanemertaken is True %}

            <h3>Name: {{Accountholder.name}}</h3>
            <div class="container">
              <div class="row">
                <div class="col">
                  {% if Accountholder.islongloantaken is True %}
                  <h4>Type of loan: Long loan</h4>
                  <h5>Amount of loan taken: &#x20b9; {{Accountholder.longloanamount|intcomma }}</h5>
                  {% endif %}
                </div>
                <div class="col">
                  {% if Accountholder.isloanemertaken is True %}
                  <h4>Type of loan: Emergency Loan</h4>
                  <h5>Amount of loan taken: &#x20b9; {{Accountholder.emerloanamount|intcomma }}</h5>
                  {% endif %}
                </div>
              </div>
            </div>
            {%else%}
            <h4>You have no loans due</h4>
            {% endif %}

            {% if Accountholder.teachingstaff is True %}
            <h4>You can apply for long loan up to &#x20b9;12,00,000</h4>
            {% endif %}
            {% if Accountholder.nonteachingstaff is True %}
            <h4>You can apply for long loan up to &#x20b9;9,00,000</h4>
            {% endif %}


          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h1><b class="card-title">Request a loan</b></h1>
            <h2 style="padding-top:50px"></h2>

            <form class=" radio" method="POST">
              <input type="radio" name="loanChoice" value="Normal loan"> Normal Loan
              <input type="radio" name="loanChoice" value="Emergency loan"> Emergency Loan
              <div class="radio">
                <div class="lw-field">
                  <input class="lw-input" autocomplete="off" name="loan_amount" id="loan_amnt" type="numeric"
                    placeholder="Enter Amount in Rs" required>
                </div>
                <button class="lw-btn"
                  onclick="md.showNotification('top','center','You will be chagrged 0.25% of the loan amount')"
                  href="{%url 'status:details'%}">Submit to admin</button>
                {% csrf_token %}
            </form>
          </div>
        </div>
      </div>
    </div>
    {% if messages %}
    <ul>
      {% for message in messages %}
      <script type="text/javascript">
        md.showNotification('bottom', 'right', "{{message}}")
      </script>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-12">
      <div class="card">
        <div class="card-header card-header-tabs card-header-primary">
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <span class="nav-tabs-title">Loans:</span>
              <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="nav-item">
                  <a class="nav-link active" href="#emergency_loan" data-toggle="tab">
                    <i class="material-icons">offline_bolt</i> Emergency Loan
                    <div class="ripple-container"></div>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#long_loan" data-toggle="tab">
                    <i class="material-icons">monetization_on</i> Long Loan
                    <div class="ripple-container"></div>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane active " id="emergency_loan">
              <table class="table">
                {%if Accountholder.isloanemertaken is True%}
                <tbody>
                  <tr>
                    <td></td>
                    <td>
                      <h2>Emergency Loan Details</h2>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan Principle: &#8377 {{Accountholder.emerloanprinciple|intcomma}}</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan Amount: &#8377 {{Accountholder.emerloanamount|intcomma}}</h4>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan Balance: &#8377 {{Accountholder.emerloanbalance|intcomma}}</h4>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan Period: {{Accountholder.emerloanperiod}} month(s)</h4>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan Interest Amount: &#8377 {{Accountholder.emerloaninterestamount|intcomma}}</h4>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Emergency Loan EMI: &#8377 {{Accountholder.emerloanemi|intcomma}}</h4>
                    </td>
                    <td class="td-actions text-right"></td>
                  </tr>
                </tbody>
                {%else%}
                <h1>Not applied for emergency loan</h1>
                {%endif%}
              </table>
            </div>
            <div class="tab-pane " id="long_loan">
              <table class="table">
                {%if Accountholder.islongloantaken is True%}
                <tbody>
                  <tr>
                    <td></td>
                    <td>
                      <h2>Long Loan Details</h2>
                    </td>
                    <td class="td-actions text-right">
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan Principle: &#8377 {{Accountholder.longloanprinciple|intcomma}}</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan Amount:&#8377 {{Accountholder.longloanamount|intcomma}}</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan Balance: &#8377 {{Accountholder.longloanbalance|intcomma}}</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan EMI: &#8377 {{Accountholder.longloanemi|intcomma}}</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan Period: {{Accountholder.longloanperiod}} month(s)</h4>
                    </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>
                      <h4>Long Loan Interest Amount: &#8377 {{Accountholder.longloaninterestamount|intcomma}}</h4>
                    </td>
                  </tr>
                </tbody>
                {%else%}
                <h1>Not applied for long loan</h1>
                {%endif%}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="col-lg-6 col-md-12">
      <div class="card">
        <div class="card-header card-header-tabs card-header-primary">
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <span class="nav-tabs-title">Previous Loans:</span>
              <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="nav-item">
                  <a class="nav-link active" href="#history_emergency_loan" data-toggle="tab">
                    <i class="material-icons">offline_bolt</i> Emergency Loan
                    <div class="ripple-container"></div>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#history_long_loan" data-toggle="tab">
                    <i class="material-icons">monetization_on</i> Long Loan
                    <div class="ripple-container"></div>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane active " id="history_emergency_loan">
              <table class="table">
                <tbody>
                    <thead>
                      {%if countemerloans != 0%}
                        <tr>
                          <th>Emergency loan date</th>
                          <th>Emergency loan amount</th>
                          <th>Emergency loan period</th>
                        </tr>
                      </thead>
                      <tbody>
                          {%for i in Emerloans%}
                        <tr>
                          <td>{{i.emerloandate}}</td>
                          <td>{{i.emerloanamount}}</td>
                          <td>{{i.emerloanperiod}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}
                      </tbody>
              </table>
            </div>
            <div class="tab-pane " id="history_long_loan">
              <table class="table">
                  <thead>
                      {%if countlongloans != 0%}
                        <tr>
                          <th>Emergency loan date</th>
                          <th>Emergency loan amount</th>
                          <th>Emergency loan period</th>
                        </tr>
                      </thead>
                      <tbody>
                          {%for i in Longloans%}
                        <tr>
                          <td>{{i.longloandate}}</td>
                          <td>{{i.longloanamount}}</td>
                          <td>{{i.longloanperiod}}</td>
                        </tr>
                        {%endfor%}
                        {%endif%}
                      </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{%endblock%}

website/status/templates/dashboard.html
{%extends 'details.html'%}
{% load humanize %}

{%block content%}

<main role="main" class="col-md-9col-lg-10 px-4">
  <div>


    <div class="card">
      <div class="card-body">

        <h1>{{Accountholder.name}} </h1>
        <h4>SAP Id: {{Accountholder.sapid}}</h4>
        <h4>DoJ: {{date}}</h4>
        <h4>Monthly Deductions: &#x20b9; {{Accountholder.sharevalue|intcomma }}<a href="#modal"> &nbsp change</a></h4>
        <h4>Total Money Deducted: &#x20b9; {{Accountholder.totalamount|intcomma }}</h4>
      </div>
    </div>

          {% if messages %}
          <ul>
             {% for message in messages %}
                   <script type="text/javascript">
                     md.showNotification('top','center' ,"{{message}}")
                   </script>
             {% endfor %}
          </ul>
          {% endif %}

    <div class="container">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h2>Fixed Deposits </h2>
              <h4>You have {{fdcount}} FD(s)</h4>
              <h4>To view FD details click <a href="../status/fixedDeposits">here</a></h4>
              <h4>Interest: {{Interests.fdinterest}} </h4>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card">
            <div class="card-body">
              <h2>Shares</h2>
              <h4>No of Shares: {{Accountholder.Noofshares}}</h4>
              <h4>Share Amount: &#x20b9; {{Accountholder.sharebalance|intcomma }}</h4>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h2>Cumulative Deposits </h2>
              <h4>Balance: &#x20b9; {{ Accountholder.cdbalance|intcomma }}</h4>
              <h4>Interest: {{Interests.cddividend}} </h4>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h2>Loan</h2>
              <ul>
                {% if Accountholder.islongloantaken or Accountholder.isloanemertaken is True %}
                <h4>Long Loan Balance: &#x20b9; {{ Accountholder.longloanbalance|intcomma  }}</h4>
                <h4>Emergency Loan Balance: &#x20b9; {{ Accountholder.emerloanbalance|intcomma  }}</h4>
                {% else %}
                <h4>You have no loans due</h4>
                <h4>Request Loan
                  <a href="../status/Loanuser" style="font-size:0.8rem;"> Loan </a>
                </h4>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>

      </div>

      <div id="modal" class="overlay">
        <div class="popup">
          <h2>Change your Monthly Deduction</h2>
          <a class="close" href="{%url 'status:details'%}">×</a>
          <div class="content">
            <form class="lw-form" method="POST" action="{%url 'status:details'%}" >
              <div class="lw-field">
                <input class="lw-input" name="new_amount" id="new_amnt" autocomplete="off" step="500" type="numeric" placeholder="Enter Amount in Rs" required>
              </div>
              <button class="lw-btn">Submit to admin</button>
              {% csrf_token %}
            </form>
          </div>
        </div>
      </div>
</main>
{%endblock%}

website/status/templates/details.html
{% load static%}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">

  <title>{%block title%}Dashboard{%endblock%}</title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!--bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.10/dist/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- Custom styles for this template -->
  <link href="{% static 'status/css/dashboard.css'%}" rel="stylesheet">
  <!-- <link href="{% static 'status/css/committee.css'%}" rel="stylesheet"> -->
  <link href="{% static 'status/css/pop.css'%}" rel="stylesheet">
  <!-- Scripts  -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{%static 'status\js\perfect-scrollbar.jquery.min.js'%}"></script>
  <script src="{%static 'status\js\bootstrap-notify.js'%}"></script>
  <script src="{%static 'status\js\script.js'%}"></script>

  <script>
md = {
showNotification: function(from, align, message) {
    type = ['', 'info', 'danger', 'success', 'warning', 'rose', 'primary'];

    // color = Math.floor((Math.random() * 6) + 1);

    $.notify({
      icon: "add_alert",
      message: message,

    }, {
      type: type[6],
      timer: 3000,
      placement: {
        from: from,
        align: align
      }
    });
  },
}

  </script>
</head>

<body class="">

  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <div class="logo">
        <h3>DJS Credit Society</h3>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item  {{dashboard}}">
            <a class="nav-link" href="{%url 'status:details'%}">
              <i class="material-icons">dashboard</i>
              Dashboard
            </a>
          </li>
          <li class="nav-item  {{share}} ">
            <a class="nav-link" href="{%url 'status:shares' %}">
              <i class="material-icons">drafts</i>
              Shares
            </a>
          </li>
          <li class="nav-item  {{fixed}}">
            <a class="nav-link" href="{%url 'status:fixedDeposits' %}">
              <i class="fa fa-lock"></i>
              Fixed Deposits
            </a>
          </li>
          <li class="nav-item {{loan}}">
            <a class="nav-link" href="{%url 'status:loanuser' %}">
            <i class="fa fa-rupee"></i>
              Loans
            </a>
          </li>
          <li class="nav-item {{investment}} ">
            <a class="nav-link" href="{%url 'status:Investment'%}">
              <i class="fa fa-line-chart" aria-hidden="true"></i>
              Total Investment
            </a>
          </li>
          <li class="nav-item {{committee}} ">
            <a class="nav-link" href="{%url 'status:committee'%}">
              <i class="fa fa-users" aria-hidden="true"></i>
              Committee
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{%url 'logout' %}">
              <i class="fa fa-sign-out" aria-hidden="true"></i>
              Sign Out
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a href="#" class="navbar-brand"></a>

          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

        </div>
      </nav>

      {%block content%}{%endblock%}

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script src="{%static 'status\js\jquery.min.js'%}"></script>
<script src="{%static 'status\js\popper.min.js'%}"></script>
<script src="{%static 'status\js\perfect-scrollbar.jquery.min.js'%}"></script>
<script src="{%static 'status\js\material-dashboard.js'%}"></script>
<script src="{%static 'status\js\bootstrap-notify.js'%}"></script>
<script src="{%static 'status\js\script.js'%}"></script>
<script src="{%static 'status\js\mat.js'%}"></script>

website/status/templates/shares.html
{%extends 'details.html'%}
{% load humanize %}

{%block title%}Shares{%endblock%}
{%block content%}

<main role="main" class="col-md-9 col-lg-12 px-4">
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title"><b>Share Certificate</b></h1>
          <h3><b>Share Holder Name:</b>{{Accountholder.name}}</h3>
          <h3><b>Share Value:</b> &#x20b9; {{Accountholder.sharevalue|intcomma }}</h3>
          <h3><b>Number of Shares: </b>{{Accountholder.Noofshares}}</h3>
          <a href="{% url 'status:GeneratePdf'%}" class="lw-btn" style="btn_color:#0b0bef" target="_blank "><i class="material-icons">picture_as_pdf</i> Save</a>
        </div>
      </div>
    </div>
  </div>
  </div>
</main>
{%endblock%}