website/csadmin/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.auth.decorators import login_required

app_name='csadmin'
urlpatterns = [
    # /status

    # nav bar urls
    path('', views.index,name="index"),
    path('members', views.members,name="members"),
    path('fixeddeposits', views.fixeddeposits,name="fixeddeposits"),
    path('loans', views.loansadmin,name="loansadmin"),
    path('change', views.change,name="change"),
    path('message', views.message,name="message"),
    path('notifications', views.notifications,name="notifications"),
    path('history',views.history,name='history'),
    path('report',views.report,name='reportlist'),

    # new create urls
    path('usercreate', login_required(views.UserCreate.as_view()),name='user_create'),
    path('account/create/', login_required(views.AccountCreate.as_view()), name='account_create'),

    # rateof interests url
    path('interests/', login_required(views.InterestsUpdate.as_view()), name='interest_update'),

    # delete user url
    path('<int:id>/delete/',login_required(views.AccountDelete.as_view()),name='User_Delete'),
    url(r'^delete/(?P<part_id>[0-9]+)/$', views.notidelete,name='Notification_Delete'),
    path('userdelete', login_required(views.UserDelete),name='user_delete'),

    # individual details update
    path('FDupdate/(?P<pk>)/', login_required(views.FDUpdate.as_view()), name='fd_update'),
    path('LongLoanupdate/(?P<pk>)/', login_required(views.LongLoanUpdate.as_view()), name='longloan_update'),
    path('EmerLoanupdate/(?P<pk>)/', login_required(views.EmerLoanUpdate.as_view()), name='emerloan_update'),
    path('Sharesupdate/(?P<pk>)/', login_required(views.SharesUpdate.as_view()), name='shares _update'),
    path('Downpayment/(?P<pk>)/', login_required(views.Downpayment.as_view()), name='downpayment_update'),
    path('FDcreate/(?P<pk>)/', login_required(views.FDCreate.as_view()), name='fd_create'),
    # path('actionUrl', views.FDUpdate.as_view(),name='fdrenew'),

    # pdf conversion
    path('accounts',login_required(views.GeneratePdf.as_view()),name="GeneratePdf"),
    path('cd',login_required(views.GenerateReport.as_view()),name="GenerateReport"),

]

website/status/urls.py
from django.urls import path
from . import views

app_name='status'
urlpatterns = [
    # /status
    path('', views.index,name="index"),
    path('details',views.details,name="details"),
    path('custlogin',views.custlogin,name="custlogin"),
    path('shares',views.shares,name="shares"),
    path('fixedDeposits',views.fixedDeposits,name="fixedDeposits"),
    path('Loanuser',views.loanuser,name="loanuser"),
    path('Investment',views.Investment,name="Investment"),
    path('committee',views.committee,name="committee"),
    path('pdf',views.GeneratePdf.as_view(),name="GeneratePdf"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from status import views
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('status.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('csadmin/', include('csadmin.urls')),
    path('',include('landingPage.urls')),
    #path('',Home.as_view()),
]

website/csadmin/models.py
from django.db import models
from status.models import Account,interests,FixedDeposits
# Create your models here.

website/status/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


# Create your models here.
class Account(models.Model):
    #schema for data to show
    accountnumber=models.IntegerField(null=False,unique=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=True)
    name=models.CharField(max_length=50,null=False)
    sapid=models.IntegerField(null=False,unique=True)
    dateofjoining=models.DateField(null=False)
    sharevalue=models.IntegerField(default=0,null=False)
    totalinvestment=models.IntegerField(default=0,null=False)
    shareamount=models.IntegerField(default=0,null=False)
    sharebalance=models.IntegerField(default=0)

    cdamount=models.IntegerField(default=0)
    cdbalance=models.IntegerField(default=0)
    #cdbalance + sharebalance = total investment
    totalamount=models.DecimalField(default=0,max_digits=10,decimal_places=2)
    #schema for shares
    Noofshares=models.IntegerField(default=0,null=True)
    #schema for Loans
    islongloantaken=models.BooleanField(default=False)
    isloanemertaken=models.BooleanField(default=False)

# main amount , the loan taken
    longloandate=models.DateField(null=True,blank=True)
    longloanamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloanprinciple=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloanperiod=models.IntegerField(blank=True,null=True,default=0)
    longloaninterestamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloanbalance=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloanadditional=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
#emi=interest + principle
    longloanemi=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)

    #emergency loan
    emerloandate=models.DateField(null=True,blank=True)
    emerloanamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    emerloanprinciple=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    emerloanperiod=models.IntegerField(blank=True,null=True,default=0)
    emerloaninterestamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    emerloanbalance=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
#emi=interest + principle
    emerloanemi=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
#downpayment
    downpayment=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    displaydownpayment=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    #schema for fixed Deposits
    FDCount=models.IntegerField(default=0,null=False)

    #teaching and nonteaching staff
    teachingstaff=models.BooleanField(default=False)
    nonteachingstaff=models.BooleanField(default=False)


    def __str__(self):
        return str(self.username)

class interests(models.Model):
    sharedividend=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    cddividend=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    fdinterest=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    emerloaninterest=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloaninterest=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    year=models.CharField(default=0,max_length=50,null=True)

class Notification(models.Model):
    notimessage=models.CharField(default=0,max_length=50,null=True)
    notidate=models.DateField(null=False,default=datetime.date.today())
    seen=models.BooleanField(default=False)
    sender=models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return str(self.sender)

class FixedDeposits(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    fdcapital=models.IntegerField(default=0,null=True)
    fddate=models.DateField(null=True,blank=True)
    fdmaturitydate=models.DateField(null=True,blank=True)
    fdnumber=models.CharField(default=0,max_length=50,null=True)

    def __str__(self):
        return str(self.username)

class HistorylongLoan(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    longloanamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    longloandate=models.DateField(null=True,blank=True)
    longloanperiod=models.IntegerField(blank=True,null=True,default=0)
#emi=interest + principle
    #emergency loan

    def __str__(self):
        return str(self.username)

class HistoryemerLoan(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    emerloanamount=models.DecimalField(blank=True,null=True,default=0,max_digits=10,decimal_places=2)
    emerloanperiod=models.IntegerField(blank=True,null=True,default=0)
    emerloandate=models.DateField(null=True,blank=True)

    def __str__(self):
        return str(self.username)

class HistoryFd(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    fdcapital=models.IntegerField(default=0,null=True)
    fddate=models.DateField(null=True,blank=True)
    fdmaturitydate=models.DateField(null=True,blank=True)
    fdnumber=models.CharField(default=0,max_length=50,null=True)

    def __str__(self):
        return str(self.username)

class sharemonth(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    Janurary=models.IntegerField(blank=True,null=True,default=0)
    february=models.IntegerField(blank=True,null=True,default=0)
    March=models.IntegerField(blank=True,null=True,default=0)
    April=models.IntegerField(blank=True,null=True,default=0)
    May=models.IntegerField(blank=True,null=True,default=0)
    June=models.IntegerField(blank=True,null=True,default=0)
    July=models.IntegerField(blank=True,null=True,default=0)
    August=models.IntegerField(blank=True,null=True,default=0)
    September=models.IntegerField(blank=True,null=True,default=0)
    October=models.IntegerField(blank=True,null=True,default=0)
    November=models.IntegerField(blank=True,null=True,default=0)
    December=models.IntegerField(blank=True,null=True,default=0)
    year=models.IntegerField(blank=True,null=True,default=0)
    sum=models.IntegerField(blank=True,null=True,default=0)
    dividend=models.FloatField(blank=True,null=True,default=0)
    def __str__(self):
        return str(self.username)

class cdmonth(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    Janurary=models.IntegerField(blank=True,null=True,default=0)
    february=models.IntegerField(blank=True,null=True,default=0)
    March=models.IntegerField(blank=True,null=True,default=0)
    April=models.IntegerField(blank=True,null=True,default=0)
    May=models.IntegerField(blank=True,null=True,default=0)
    June=models.IntegerField(blank=True,null=True,default=0)
    July=models.IntegerField(blank=True,null=True,default=0)
    August=models.IntegerField(blank=True,null=True,default=0)
    September=models.IntegerField(blank=True,null=True,default=0)
    October=models.IntegerField(blank=True,null=True,default=0)
    November=models.IntegerField(blank=True,null=True,default=0)
    December=models.IntegerField(blank=True,null=True,default=0)
    year=models.IntegerField(blank=True,null=True,default=0)
    sum=models.IntegerField(blank=True,null=True,default=0)
    dividend=models.FloatField(blank=True,null=True,default=0)

    def __str__(self):
        return str(self.username)

class year(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True,unique=False)
    s_encode=models.CharField(max_length=20,blank=True,null=True,default=0)
    cd_encode=models.CharField(max_length=20,blank=True,null=True,default=0)
    year=models.CharField(max_length=20,blank=True,null=True,default=0)

website/csadmin/forms.py
from django import forms
from django.contrib.auth.models import User
from status.models import Account,interests,Notification,FixedDeposits,HistorylongLoan,HistoryemerLoan,HistoryFd

Loan_choice=[
    ('long_loan','Long_Loan'),
    ('emergency_loan', 'Emergency_Loan'),
    ('cd', 'CD'),
    ('share', 'Share'),
]
class dateRangeForm(forms.Form):
    startdate= forms.DateField()
    enddate=forms.DateField()
    userA=forms.CharField()
    Choice = forms.CharField(widget=forms.RadioSelect(choices=Loan_choice))

class InterestsForm(forms.ModelForm):
    class Meta:
        model=interests
        fields=('sharedividend','cddividend','fdinterest','emerloaninterest','longloaninterest','year')

class AccountForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=('accountnumber','username','name','sapid','dateofjoining','teachingstaff','nonteachingstaff','sharevalue')

class NewUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','password','first_name','last_name','email')

class FDUpdateForm(forms.ModelForm):
    class Meta:
        model=FixedDeposits
        fields=('username','fdcapital','fdmaturitydate')

class ShareUpdateForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=('username','sharevalue')

class LongLoanUpdateForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=('username','longloanamount','longloanperiod','longloanadditional','longloandate')

class EmerLoanUpdateForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=('username','emerloanamount','emerloanperiod','emerloandate')

class DownPaymentForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=('username','downpayment')

class MessengerForm(forms.Form):
    fmessage=forms.CharField(widget=forms.TextInput)

class SecretkeyForm(forms.Form):
    fchairmankey=forms.IntegerField()
    fsecretarykey=forms.IntegerField()

website/csadmin/templates/AccountCreate.html
{%extends 'base.html'%}
{%block title%}Accounts{%endblock%}
{%block content%}
<h2>ADD Account Details</h2>
<div class="container-fluid">
  <div class="row">


    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <form action="" method="post">
            {% csrf_token %}
            <table>
              <tr><th><label for="id_accountnumber">Accountnumber:</label></th><td><input type="number" name="accountnumber" value={{acc_nu}} required id="id_accountnumber"></td></tr>
              <tr><th><label for="id_username">Username:</label></th><td>
                <select name="username" required id="id_username">
                {%for i in user reversed%}
                <option value={{i.id}}>{{i.username}}</option>
                {%endfor%}

              </select>
            </td></tr>
              <tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" maxlength="50" required id="id_name" value="{{fullname}}"></td></tr>
              <tr><th><label for="id_sapid">Sapid:</label></th><td><input type="number" name="sapid" required id="id_sapid"></td></tr>
              <tr><th><label for="id_dateofjoining">Dateofjoining:</label></th><td><input type="date" name="dateofjoining" value={{date_today|date:"Y-m-d"}} required id="id_dateofjoining"></td></tr>
              <tr><th><label for="id_teachingstaff">Teachingstaff:</label></th><td><input type="checkbox" name="teachingstaff" id="id_teachingstaff"></td></tr>
              <tr><th><label for="id_nonteachingstaff">Nonteachingstaff:</label></th><td><input type="checkbox" name="nonteachingstaff" id="id_nonteachingstaff"></td></tr>
              <tr><th><label for="id_sharevalue">Sharevalue:</label></th><td><input type="number" name="sharevalue" value="0" required id="id_sharevalue"></td></tr>
          </table>
            <div class="form-group " style="margin-top:20px">
              <div class="col-sm-offset-2 col-sm-10">
                  <button class="btn btn-primary ">
                      <i class="material-icons">check</i> SAVE
                    </button>
              </div>
            </div>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>
{%endblock%}

website/csadmin/templates/bank.html
{%extends 'base.html'%}

{%block title%}Bank{%endblock%}
{%block content%}

<main role="main" class="col-md-8 col-lg-12 px-4">
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h1 class="h2">List Of Current FDs</h1>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    {%for i in Interests%}
                    <h3>FD rate of interest = {{i.fdinterest}}</h3>{%endfor%}
                    <tr>
                      <th>A/C No.</th>
                      <th>SapId</th>
                      <th>Name</th>
                      <th>FD Capital</th>
                      <th>Maturity Date</th>

                    </tr>
                  </thead>
                  <tbody>

              {%for i in Banks%}
                <tr>
                  <td>{{i.accountnumber}}</td>
                  <td>{{i.sapid}}</td>
                  <td>{{i.name}}</td>
                  <td>{{i.fdcapital}}</td>
                  <td>{{i.fdmaturitydate}}</td>

                </tr>

              {%endfor%}

              </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
  </div>
  </div>
</main>
{%endblock%}

website/csadmin/templates/base.html
{% load static%}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">

  <title>{%block title%}Dashboard{%endblock%}</title>

  <!-- template for side navbar -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!--bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.10/dist/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/0.9.0/jquery.mask.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- Custom styles for this template -->
  <link href="{% static 'status/css/dashboard.css'%}" rel="stylesheet">
  <!-- <link href="{% static 'status/css/committee.css'%}" rel="stylesheet"> -->
  <link href="{% static 'status/css/pop.css'%}" rel="stylesheet">
  <!-- Scripts  -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{%static 'status\js\bootstrap-notify.js'%}"></script>
  <script src="{%static 'status\js\script.js'%}"></script>
  <script src="{%static 'stats\js\test.js'%}"></script>
  <script type="text/javascript">

  </script>
  <script type="text/javascript">

  // inpu mtasking
$('.mask-date').mask("00/00/0000", {
  placeholder: "__-__-____"
});
$('.mask-money').mask('00,00,000', {
  reverse: true
});

  </script>
  <script>
  md = {
  showNotification: function(from, align, message) {
    type = ['', 'info', 'danger', 'success', 'warning', 'rose', 'primary'];

    // color = Math.floor((Math.random() * 6) + 1);

    $.notify({
      icon: "add_alert",
      message: message,

    }, {
      type: type[6],
      timer: 3000,
      placement: {
        from: from,
        align: align
      }
    });
  },
  }

  </script>
</head>

<body class="">

    <div class="wrapper ">
      <div class="sidebar" data-color="purple" data-background-color="white" data-image="">
        <div class="logo">
          <h3>DJS Credit Society</h3>
        </div>
        <div class="sidebar-wrapper">
          <ul class="nav">
            <li class="nav-item  {{dashb}}">
              <a class="nav-link" href="{%url 'csadmin:index'%}">
                <i class="material-icons">dashboard</i>
                Dashboard
              </a>
            </li>
            <li class="nav-item  {{member}} ">
              <a class="nav-link" href="{%url 'csadmin:members' %}">
                <i class="fa fa-group"></i>
                 Members
              </a>
            </li>
            <li class="nav-item  {{Bank}}">
              <a class="nav-link " href="{%url 'csadmin:fixeddeposits' %}">
                <i class="fa fa-lock"></i>
                Fixed Deposits
              </a>
            </li>
            <li class="nav-item {{loan}}">
              <a class="nav-link" href="{%url 'csadmin:loansadmin' %}">
                <i class="fa fa-rupee"></i>
                Loans
              </a>
            </li>
            <li class="nav-item {{money}} ">
              <a class="nav-link" href="{%url 'csadmin:change'%}">
                <i class="fa fa-refresh"></i>
                Change
              </a>
            </li>
            <li class="nav-item {{message}} ">
              <a class="nav-link" href="{%url 'csadmin:message'%}">
                <i class="fa fa-paper-plane"></i>
                Message
              </a>
            </li>
            <li class="nav-item {{notifications}} ">
              <a class="nav-link" href="{%url 'csadmin:notifications'%}">
              <i class="fa fa-bell"></i>
              <span>Notifications</span>
              {%if noofnoti > 0 %}
              <span class="badge badge-pill badge-warning notification">{{noofnoti}}</span>
              {% endif %}
            </a>
            </li>
            <li class="nav-item {{history}} ">
              <a class="nav-link" href="{%url 'csadmin:history'%}">
                <i class="fa fa-history"></i>
                History
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{%url 'logout' %}">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
                Sign Out
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper">
              <a href="#" class="navbar-brand"></a>

            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
            </button>

          </div>
        </nav>
        {%block content%}{%endblock%}

      </div>
    </div>
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <script src="{%static 'status\js\jquery.min.js'%}"></script>
  <script src="{%static 'status\js\popper.min.js'%}"></script>
  <script src="{%static 'status\js\perfect-scrollbar.jquery.min.js'%}"></script>
  <script src="{%static 'status\js\material-dashboard.js'%}"></script>
  <script src="{%static 'status\js\bootstrap-notify.js'%}"></script>
  <script src="{%static 'status\js\script.js'%}"></script>
  <script src="{%static 'status\js\mat.js'%}"></script>
  </html>

website/csadmin/templates/longloan_update_form.html
{%extends 'base.html'%}
{%block title%}Accounts{%endblock%}
{%block content%}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="card card-stats">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">content_copy</i>
          </div>
          <h3 class="card-title" style="text-align:left;"><b>Add a Long Loan</b>
          </h3>
          <form action="" method="post">
            {% csrf_token %}
            <table>
              {%if islongloantaken is False%}
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th><label for="id_username" class="bmd-label-floating">Username:</label></th>
                    <td><select name="username" class="form-control" required id="id_username">
                        <option value={{Userid}} selected>{{username}}</option>
                      </select></td>
                  </div>
                </div>
              </tr>
              <!-- <tr>
                <th><label for="id_islongloantaken">Is Long Loan Taken:</label></th>
                <td><input type="checkbox" name="islongloantaken" id="id_islongloantaken"></td>
              </tr> -->
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th> <label for="id_longloanamount" class="bmd-label-floating">Long Loan Amount:</label></th>
                    <td> <input type="number" name="longloanamount" value="{{longloanamt}}" step="100"
                        id="id_longloanamount" class="form-control" min="0" max="{{maxloan}}"></td>
                  </div>
                </div>
              </tr>
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th> <label for="id_longloanperiod" class="bmd-label-floating">Long Loan Period(In Months):</label>
                    </th>
                    <td> <input type="number" name="longloanperiod" value="{{longloanprd}}" step="1"
                        id="id_longloanperiod" class="form-control"></td>
                  </div>
                </div>
              </tr>
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th> <label for="id_longloandate" class="bmd-label-floating">Long Loan Date:</label>
                    </th>
                    <td> <input type="date" name="longloandate" value={{longloandt|date:"Y-m-d"}}
                        id="id_longloandate" class="form-control"></td>
                  </div>
                </div>
              </tr>
              {%elif islongloantaken is True and validate is True%}
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th><label for="id_username" class="bmd-label-floating">Username:</label></th>
                    <td><select name="username" class="form-control" required id="id_username">
                        <option value={{Userid}} selected>{{username}}</option>
                      </select></td>
                  </div>
                </div>
              </tr>
              <!-- <tr>
                <th><label for="id_islongloantaken">Is Long Loan Taken:</label></th>
                <td><input type="checkbox" name="islongloantaken" id="id_islongloantaken"></td>
              </tr> -->
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th> <label for="id_longloanadditional" class="bmd-label-floating">Long Loan Addition:</label></th>
                    <td> <input type="number" name="longloanadditional" value="{{longloanadd}}" step="100"
                        id="id_longloanadditional" class="form-control"></td>
                  </div>
                </div>
              </tr>
              {%elif validate is False%}
              <tr>
                <div class="col-md-4">
                  <div class="form-group">
                    <th> <label>Previous Loan has not been paid</label>
                    </th>
                  </div>
                </div>
              </tr>
              {% endif %}
            </table>
            {%if islongloantaken is False%}
            <div class="form-group " style="margin-top:20px">
              <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary ">
                  <i class="material-icons">check</i> SAVE DETAILS
                </button>
              </div>
            </div>
            {%elif islongloantaken is True and validate is True%}
            <div class="form-group " style="margin-top:20px">
              <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary ">
                  <i class="material-icons">check</i> SAVE DETAILS
                </button>
              </div>
            </div>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}